config/routes.rb
Rails.application.routes.draw do

  resources :comments
  root "suggestions#home"
  resources :suggestions

  get "signup", to: "users#new"
  resources :users

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :title, presence:true, length: { minimum:3 }
  validates :description, presence:true, length: { minimum:10, maximum:300 }
  validates :user_id, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :suggestions, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :username, presence:true,uniqueness:{case_sensitive:false}, length: {minimum:3,maximum:25}

  VALID_EMAIL_REGEX = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i
  validates :email, presence:true, length: {maximum:100}, uniqueness:{case_sensitive:false},format:{with:VALID_EMAIL_REGEX}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #to make the method available in views
  helper_method :current_user, :logged_in?

  def current_user
    @current_user||User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in first to perform the action"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You've been successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There is something wrong with your login information"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:danger] = "You've been logged out"
    redirect_to login_path
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only:[:edit,:show,:destroy,:update]
  # before_action :require_user, except:[:index,:show]
  before_action :require_same_user, only:[:edit,:update,:delete]

  def home

  end

  def index
    @suggestions = Suggestion.all
  end

  def new
    @suggestion = Suggestion.new
  end

  def create
    # render plain: params[:suggestion].inspect
    @suggestion = Suggestion.new (suggestion_params)
    @suggestion.user = current_user
    if @suggestion.save
      flash[:success] = "Successfully created..."
      redirect_to suggestion_path(@suggestion)
    else
      render "new"
    end
  end

  def edit

  end

  def update
    if @suggestion.update(suggestion_params)
      flash[:success] = "Successfully updated..."
      redirect_to suggestion_path(@suggestion)
    else
      render "edit"
    end
  end

  def show

  end

  def destroy
    @suggestion.destroy
    flash[:danger] = "Successfully deleted..."

    redirect_to suggestions_path
  end

  private
  def set_suggestion
    @suggestion = Suggestion.find(params[:id])
  end

  def suggestion_params
    params.require(:suggestion).permit(:title,:description)
  end

  def require_same_user
    if current_user != @suggestion.user and !current_user.admin?
      flash[:danger] = "You can only edit or update your suggestion"
      redirect_to suggestions_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:update,:delete,:show]
  before_action :require_same_user, only: [:update,:delete,:edit,:destroy]
  before_action :require_admin, only: [:destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Hello #{@user.username}, you've been successfully signed up"
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def edit

  end

  def update

    if @user.update(user_params)
      flash[:success] = "You've been successfully updated"
      redirect_to suggestions_path
    else
      render "edit"
    end
  end

  def show

  end

  def destroy
    @user = User.find_by(params[:id])
    @user.destroy
    flash[:danger] = "You've succesfully deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You only can edit or update your own profile"
      redirect_to suggestions_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin can use delete"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <% flash.each do|name,msg|%>
    <div class='alert alert-<%= "#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">X</a>
      <%= content_tag :div, msg, :id=>"flash_#{name}" if msg.is_a?(String)%>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if logged_in? %>
        <%= link_to "Suggestion App", suggestions_path, class: "navbar-brand", id:"logo"%>
      <% else %>
        <%= link_to "Suggestion App", root_path, class: "navbar-brand", id:"logo"%>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li><%= link_to "Home", suggestions_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Suggestion", new_suggestion_path%></li>
            <li><%= link_to "Edit Suggestion", edit_suggestion_path(current_user) %></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Admin" if current_user.admin?%> Profile<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile", user_path(current_user)%></li>
              <li><%= link_to "Edit your profile", edit_user_path(current_user)%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete%></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "Login", login_path%></li>
            <li><%= link_to "Sign up", signup_path%></li>
          <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuggestionApp</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navigation"%>


  <div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>

  <%= debug(params) if Rails.env.development?%>

</body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h4>
            There are <%= pluralize(obj.errors.count, "error")%>, please correct your input:
          </h4>

          <div class="panel-body">
            <% obj.errors.full_messages.each do |msg|%>
              <ul>
                <li><%= msg %></li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/suggestions/_form.html.erb
<%= render "shared/error",obj:@suggestion %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@suggestion,:html => {class:"form-horizontal",role:"form"}) do|f|%>
      <div class="form-group">
        <div class="col-md-2">
            <%= f.label :title%>
        </div>

        <div class="col-md-8">
          <%= f.text_field :title, class:"form-control",placeholder:"Enter your title",autofocus:"true"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-2">
          <%= f.label :description%>
        </div>

        <div class="col-md-8">
          <%= f.text_area :description, class:"form-control",rows:"10", placeholder:"Enter your description"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
          <%= f.submit class:"btn btn-success"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
          <%= link_to "Cancel", suggestions_path, class: "btn btn-primary" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/suggestions/_suggestion.html.erb
<% obj.each do|suggestion|%>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="well well-lg">
        <h3><%= link_to suggestion.title, suggestion_path(suggestion)%></h3>
        <div class="description">
          <p><%= truncate(suggestion.description, length: 100) %></p>
        </div>
        <div class="user">
          <ul class="list-inline">
            <li><small><i class="fa fa-user"></i> <%=link_to suggestion.user.username, user_path(suggestion.user)%></small></li>
            <li><small><i class="fa fa-clock-o"></i> <%= time_ago_in_words(suggestion.created_at)%> ago</small></li>
            <li><small>last updated <%= time_ago_in_words(suggestion.created_at)%></small></li>
          </ul>

        </div>
        <% if logged_in? && (suggestion.user == current_user || current_user.admin?)%>
          <div class="action">
            <%= link_to "Edit", edit_suggestion_path(suggestion), class:"btn btn-primary"%>
            <%= link_to "Delete", suggestion_path(suggestion), method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-danger"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Edit existing suggestion</h1>
<%= render "form" %>

app/views/suggestions/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to Suggestion App</h1>
  <%= link_to "Try Us Now", new_user_path , class: "btn btn-warning"%>
</div>

app/views/suggestions/index.html.erb
<h1>All Suggestions</h1>
<%= link_to "+ New Suggestion", new_suggestion_path%>

<%= render "suggestion", obj:@suggestions%>

app/views/suggestions/new.html.erb
<h1 class="text-center">Create Your Suggestion</h1>
<%= render "form"%>

app/views/suggestions/show.html.erb
<h1 class="text-center"><%= @suggestion.title %></h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="well">
        <p><%= simple_format(@suggestion.description) %></p>
        <div class="user">

          <ul class="list-inline">
            <li>created by <small><i class="fa fa-user"></i> <%=link_to @suggestion.user.username, user_path(@suggestion.user)%></small></li>
            <li><small><i class="fa fa-clock-o"></i> <%= time_ago_in_words(@suggestion.created_at)%> ago</small></li>
            <li><small>last updated <%= time_ago_in_words(@suggestion.created_at)%></small></li>
          </ul>

          <% if logged_in? && (current_user == @suggestion.user || current_user.admin?) %>
          <div class="action">
            <%= link_to "Edit", edit_suggestion_path(@suggestion), class:"btn btn-primary" %>
            <%= link_to "Delete", suggestions_path(@suggestion), method: :delete, data: {confirm:"Are you sure?"}, class:"btn btn-danger"%>
            <%= link_to "View All Suggestions", suggestions_path, class:"btn btn-success"%>
          </div>
    </div>

  </div>
</div>

app/views/users/_form.html.erb
<%= render "shared/error",obj:@user %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@user,:html => {class:"form-horizontal",role:"form"}) do|f|%>
      <div class="form-group">
        <div class="col-md-2">
            <%= f.label :username%>
        </div>

        <div class="col-md-8">
          <%= f.text_field :username, class:"form-control",placeholder:"Enter your username",autofocus:"true"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-2">
          <%= f.label :email%>
        </div>

        <div class="col-md-8">
          <%= f.email_field :email, class:"form-control", placeholder:"Enter your email"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-2">
          <%= f.label :password%>
        </div>

        <div class="col-md-8">
          <%= f.password_field :password, class:"form-control", placeholder:"Enter your password"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
          <%= f.submit(@user.new_record? ? "Sign Up": "Update Account",class:"btn btn-success")%>
        </div>
      </div>


    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit your account</h1>
<%= render "form"%>

app/views/users/index.html.erb
<h1> All User</h1>

<% @users.each do|user|%>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="well">
        <ul class="list">
          <li><%= link_to user.username, user_path(user) %></li>
          <li><%= pluralize(user.suggestions.count,"suggestion") if user.suggestions%></li>
          <% if !current_user.admin? || current_user.admin?%>
          <li><%= link_to "Delete User",user_path(user),method: :delete,data: {confirm:"Are you sure want to delete this user and all their articles"}%></li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 class="text-center">Sign Up</h1>
<%= render "form"%>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.username%>'s profile</h1>
  <small><i class="fa fa-pencil"></i> <%= pluralize(@user.suggestions.count, "suggestion")%></small>
</div>

<% if @user.suggestions.count != 0 %>
  <%= render "suggestions/suggestion", obj:@user.suggestions%>
<% else %>
  <div class="well">
    <p>There is no suggestion you create</p>
    <%= link_to "Create New Suggestion", new_suggestion_path%>
  </div>

<% end %>